# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Build & Deploy

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - "*"
      - "!live"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "live"
  cancel-in-progress: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write


jobs:
#  build-test:
#    uses: ./.github/workflows/part_run_tests.yaml
#  deploy:
#    needs: build-test
#    secrets: inherit
#    uses: ./.github/workflows/part_deploy.yaml
  docker-backend:
#    needs: deploy
    secrets: inherit
    uses: ./.github/workflows/part_docker_push.yaml
    with:
      image_name: job-management-backend
      dockerfile: backend.Dockerfile
  docker-frontend:
#    needs: deploy
    secrets: inherit
    uses: ./.github/workflows/part_docker_push.yaml
    with:
      image_name: job-management-frontend
      dockerfile: frontend.Dockerfile
      backend-api_url: https://api-job.servyy.duckdns.org/
