name: Deploy to Live branch

on:
  workflow_call:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  live:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 🎉 Push to stable branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: live
          FOLDER: .
          # https://github.com/ad-m/github-push-action/issues/96
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
