name: Run Python tests

on:
  workflow_call:

env:
  python-version: '3.12'
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      fail-fast: true

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f test_requirements.txt ]; then pip install -r test_requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --show-source --max-complexity=11 --max-line-length=127 --statistics --exclude .web
      - name: Test with pytest
        run: |
          pytest
