name: Deploy to Live branch

on:
  workflow_call:

jobs:
  live:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 🎉 Push to live branch
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: live
          github_token: ${{ secrets.GITHUB_TOKEN }}
